#![doc = "Peripheral access API for WB32FQ95 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDG();
    fn PVD();
    fn TAMPER();
    fn RTC();
    fn FMC();
    fn RCC();
    fn EXTI0();
    fn EXTI1();
    fn EXTI2();
    fn EXTI3();
    fn EXTI4();
    fn DMAC1();
    fn DMAC2();
    fn ADC();
    fn USB();
    fn USB_DMA();
    fn EXTI9_5();
    fn TIM1_BRK();
    fn TIM1_UP();
    fn TIM1_TRG_COM();
    fn TIM1_CC();
    fn TIM2();
    fn TIM3();
    fn TIM4();
    fn I2C1();
    fn I2C2();
    fn QSPI();
    fn SPIM2();
    fn SPIS1();
    fn SPIS2();
    fn UART1();
    fn UART2();
    fn UART3();
    fn EXTI15_10();
    fn RTCAlarm();
    fn USBP_WKUP();
    fn I2S();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 37] = [
    Vector { _handler: WWDG },
    Vector { _handler: PVD },
    Vector { _handler: TAMPER },
    Vector { _handler: RTC },
    Vector { _handler: FMC },
    Vector { _handler: RCC },
    Vector { _handler: EXTI0 },
    Vector { _handler: EXTI1 },
    Vector { _handler: EXTI2 },
    Vector { _handler: EXTI3 },
    Vector { _handler: EXTI4 },
    Vector { _handler: DMAC1 },
    Vector { _handler: DMAC2 },
    Vector { _handler: ADC },
    Vector { _handler: USB },
    Vector { _handler: USB_DMA },
    Vector { _handler: EXTI9_5 },
    Vector { _handler: TIM1_BRK },
    Vector { _handler: TIM1_UP },
    Vector {
        _handler: TIM1_TRG_COM,
    },
    Vector { _handler: TIM1_CC },
    Vector { _handler: TIM2 },
    Vector { _handler: TIM3 },
    Vector { _handler: TIM4 },
    Vector { _handler: I2C1 },
    Vector { _handler: I2C2 },
    Vector { _handler: QSPI },
    Vector { _handler: SPIM2 },
    Vector { _handler: SPIS1 },
    Vector { _handler: SPIS2 },
    Vector { _handler: UART1 },
    Vector { _handler: UART2 },
    Vector { _handler: UART3 },
    Vector {
        _handler: EXTI15_10,
    },
    Vector { _handler: RTCAlarm },
    Vector {
        _handler: USBP_WKUP,
    },
    Vector { _handler: I2S },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Window watchdog interrupt"]
    WWDG = 0,
    #[doc = "1 - PVD through EXTI line detection interrupt"]
    PVD = 1,
    #[doc = "2 - Tamper interrupt"]
    TAMPER = 2,
    #[doc = "3 - RTC global interrupt"]
    RTC = 3,
    #[doc = "4 - FMC global interrupt"]
    FMC = 4,
    #[doc = "5 - RCC global interrupt"]
    RCC = 5,
    #[doc = "6 - EXTI line 0 interrupt"]
    EXTI0 = 6,
    #[doc = "7 - EXTI line 1 interrupt"]
    EXTI1 = 7,
    #[doc = "8 - EXTI line 2 interrupt"]
    EXTI2 = 8,
    #[doc = "9 - EXTI line 3 interrupt"]
    EXTI3 = 9,
    #[doc = "10 - EXTI line 4 interrupt"]
    EXTI4 = 10,
    #[doc = "11 - DMAC1 global interrupt"]
    DMAC1 = 11,
    #[doc = "12 - DMAC2 global interrupt"]
    DMAC2 = 12,
    #[doc = "13 - ADC global interrupt"]
    ADC = 13,
    #[doc = "14 - USB global interrupt"]
    USB = 14,
    #[doc = "15 - USB DMA interrupt"]
    USB_DMA = 15,
    #[doc = "16 - EXTI line\\[9:5\\] interrupts"]
    EXTI9_5 = 16,
    #[doc = "17 - TIM1 break interrupt"]
    TIM1_BRK = 17,
    #[doc = "18 - TIM1 update interrupt"]
    TIM1_UP = 18,
    #[doc = "19 - TIM1 trigger and commutation interrupt"]
    TIM1_TRG_COM = 19,
    #[doc = "20 - TIM1 capture/compare interrupt"]
    TIM1_CC = 20,
    #[doc = "21 - TIM2 global interrupt"]
    TIM2 = 21,
    #[doc = "22 - TIM3 global interrupt"]
    TIM3 = 22,
    #[doc = "23 - TIM4 global interrupt"]
    TIM4 = 23,
    #[doc = "24 - I2C1 global interrupt"]
    I2C1 = 24,
    #[doc = "25 - I2C2 global interrupt"]
    I2C2 = 25,
    #[doc = "26 - QSPI global interrupt"]
    QSPI = 26,
    #[doc = "27 - SPIM2 global interrupt"]
    SPIM2 = 27,
    #[doc = "28 - SPIS1 global interrupt"]
    SPIS1 = 28,
    #[doc = "29 - SPIS2 global interrupt"]
    SPIS2 = 29,
    #[doc = "30 - UART1 global interrupt"]
    UART1 = 30,
    #[doc = "31 - UART2 global interrupt"]
    UART2 = 31,
    #[doc = "32 - UART3 global interrupt"]
    UART3 = 32,
    #[doc = "33 - EXTI line\\[15:10\\] interrupts"]
    EXTI15_10 = 33,
    #[doc = "34 - RTC alarm through EXTI line interrupt"]
    RTCAlarm = 34,
    #[doc = "35 - USB pin wake-up global interrupt"]
    USBP_WKUP = 35,
    #[doc = "36 - I2S global interrupt"]
    I2S = 36,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "General-purpose I/O port A"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "General-purpose I/O port A"]
pub mod gpioa;
#[doc = "General-purpose I/O port B"]
pub type Gpiob = crate::Periph<gpioa::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "General-purpose I/O port B"]
pub use self::gpioa as gpiob;
#[doc = "General-purpose I/O port C"]
pub type Gpioc = crate::Periph<gpioa::RegisterBlock, 0x4000_0800>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "General-purpose I/O port C"]
pub use self::gpioa as gpioc;
#[doc = "General-purpose I/O port D"]
pub type Gpiod = crate::Periph<gpioa::RegisterBlock, 0x4000_0c00>;
impl core::fmt::Debug for Gpiod {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiod").finish()
    }
}
#[doc = "General-purpose I/O port D"]
pub use self::gpioa as gpiod;
#[doc = "Power control. ANAKEY1/ANAKEY2 unlock write access to the ANCTL block."]
pub type Pwr = crate::Periph<pwr::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Pwr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwr").finish()
    }
}
#[doc = "Power control. ANAKEY1/ANAKEY2 unlock write access to the ANCTL block."]
pub mod pwr;
#[doc = "Analog control block (holds HSE and PLL control). Write access is gated by PWR.ANAKEY1/ANAKEY2."]
pub type Anctl = crate::Periph<anctl::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Anctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Anctl").finish()
    }
}
#[doc = "Analog control block (holds HSE and PLL control). Write access is gated by PWR.ANAKEY1/ANAKEY2."]
pub mod anctl;
#[doc = "Reset and clock control"]
pub type Rcc = crate::Periph<rcc::RegisterBlock, 0x4001_0c00>;
impl core::fmt::Debug for Rcc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcc").finish()
    }
}
#[doc = "Reset and clock control"]
pub mod rcc;
#[doc = "Flash cache control (holds the flash wait-state configuration)"]
pub type Cache = crate::Periph<cache::RegisterBlock, 0x4001_5400>;
impl core::fmt::Debug for Cache {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cache").finish()
    }
}
#[doc = "Flash cache control (holds the flash wait-state configuration)"]
pub mod cache;
#[doc = "Special function macro. Also holds the USB PHY port control registers (USBPCON enables the USB transceiver)."]
pub type Sfm = crate::Periph<sfm::RegisterBlock, 0x4001_4c00>;
impl core::fmt::Debug for Sfm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sfm").finish()
    }
}
#[doc = "Special function macro. Also holds the USB PHY port control registers (USBPCON enables the USB transceiver)."]
pub mod sfm;
#[doc = "Advanced-control timer"]
pub type Tim1 = crate::Periph<tim1::RegisterBlock, 0x4000_1c00>;
impl core::fmt::Debug for Tim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim1").finish()
    }
}
#[doc = "Advanced-control timer"]
pub mod tim1;
#[doc = "General-purpose timer 2"]
pub type Tim2 = crate::Periph<tim1::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Tim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim2").finish()
    }
}
#[doc = "General-purpose timer 2"]
pub use self::tim1 as tim2;
#[doc = "General-purpose timer 3"]
pub type Tim3 = crate::Periph<tim1::RegisterBlock, 0x4000_2400>;
impl core::fmt::Debug for Tim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim3").finish()
    }
}
#[doc = "General-purpose timer 3"]
pub use self::tim1 as tim3;
#[doc = "General-purpose timer 4"]
pub type Tim4 = crate::Periph<tim1::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for Tim4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim4").finish()
    }
}
#[doc = "General-purpose timer 4"]
pub use self::tim1 as tim4;
#[doc = "Serial peripheral interface master 2"]
pub type Spim2 = crate::Periph<spim2::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Spim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim2").finish()
    }
}
#[doc = "Serial peripheral interface master 2"]
pub mod spim2;
#[doc = "Quad serial peripheral interface"]
pub type Qspi = crate::Periph<spim2::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Qspi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qspi").finish()
    }
}
#[doc = "Quad serial peripheral interface"]
pub use self::spim2 as qspi;
#[doc = "Serial peripheral interface slave 1"]
pub type Spis1 = crate::Periph<spim2::RegisterBlock, 0x4000_3400>;
impl core::fmt::Debug for Spis1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1").finish()
    }
}
#[doc = "Serial peripheral interface slave 1"]
pub use self::spim2 as spis1;
#[doc = "Serial peripheral interface slave 2"]
pub type Spis2 = crate::Periph<spim2::RegisterBlock, 0x4000_9400>;
impl core::fmt::Debug for Spis2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis2").finish()
    }
}
#[doc = "Serial peripheral interface slave 2"]
pub use self::spim2 as spis2;
#[doc = "Universal asynchronous receiver/transmitter 3"]
pub type Uart3 = crate::Periph<uart3::RegisterBlock, 0x4000_8400>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "Universal asynchronous receiver/transmitter 3"]
pub mod uart3;
#[doc = "Universal asynchronous receiver/transmitter 1"]
pub type Uart1 = crate::Periph<uart3::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "Universal asynchronous receiver/transmitter 1"]
pub use self::uart3 as uart1;
#[doc = "Universal asynchronous receiver/transmitter 2"]
pub type Uart2 = crate::Periph<uart3::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "Universal asynchronous receiver/transmitter 2"]
pub use self::uart3 as uart2;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOD"]
    pub gpiod: Gpiod,
    #[doc = "PWR"]
    pub pwr: Pwr,
    #[doc = "ANCTL"]
    pub anctl: Anctl,
    #[doc = "RCC"]
    pub rcc: Rcc,
    #[doc = "CACHE"]
    pub cache: Cache,
    #[doc = "SFM"]
    pub sfm: Sfm,
    #[doc = "TIM1"]
    pub tim1: Tim1,
    #[doc = "TIM2"]
    pub tim2: Tim2,
    #[doc = "TIM3"]
    pub tim3: Tim3,
    #[doc = "TIM4"]
    pub tim4: Tim4,
    #[doc = "SPIM2"]
    pub spim2: Spim2,
    #[doc = "QSPI"]
    pub qspi: Qspi,
    #[doc = "SPIS1"]
    pub spis1: Spis1,
    #[doc = "SPIS2"]
    pub spis2: Spis2,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            gpiod: Gpiod::steal(),
            pwr: Pwr::steal(),
            anctl: Anctl::steal(),
            rcc: Rcc::steal(),
            cache: Cache::steal(),
            sfm: Sfm::steal(),
            tim1: Tim1::steal(),
            tim2: Tim2::steal(),
            tim3: Tim3::steal(),
            tim4: Tim4::steal(),
            spim2: Spim2::steal(),
            qspi: Qspi::steal(),
            spis1: Spis1::steal(),
            spis2: Spis2::steal(),
            uart3: Uart3::steal(),
            uart1: Uart1::steal(),
            uart2: Uart2::steal(),
        }
    }
}
