// SPDX-License-Identifier: GPL-2.0-or-later
//! Autocorrect — fix a common typo the moment it is typed in full.
//!
//! Each scan's finished report is fed to [`record_report`](Autocorrect::record_report)
//! (from [`crate::keymap::compute_report`], *after* the report fold). Newly-emitted basic
//! keys are diffed against the previous scan's emitted set, so the rolling word buffer is
//! built from exactly the keys the host receives — letters accumulate, Backspace shortens,
//! any other key is a word boundary that clears it. After each letter the buffer is matched
//! against a compiled-in **trie** of typo→correction pairs (`build.rs` turns the readable
//! [`DICT`](../build.rs) into the flat node arrays `include!`d below — QMK's
//! `generate-autocorrect-data` approach). The walk is O(buffer length), independent of
//! dictionary size.
//!
//! # Why record *after* the fold
//!
//! The report fold ([`crate::features::run_on_report`]) — SOCD cleanup and key overrides —
//! can swap a trigger letter for another key, fold it into a modifier, or drop it entirely
//! (`NONE`). Recording the pre-fold key would build the buffer from keys the host may never
//! receive: a dropped letter would over-count the backspaces (deleting into preceding text),
//! a swapped letter would match a typo never actually typed. Diffing the *emitted* NKRO
//! bitmap instead means the buffer is always exactly what the host committed, so the
//! backspace count and the match are correct by construction.
//!
//! # The correction, and concurrent keystrokes
//!
//! On a whole-word match the correction is injected over the following scans: a tap of
//! Backspace for every typed letter but the suppressed trigger, then a tap of each
//! correction letter. Playback runs in [`Feature::on_overlay`], which rewrites the finished
//! report so only the synthesised keystroke reaches the host — the physical keys held during
//! the burst are masked. Each frame dwells [`FRAME_DWELL`] scans so a host poll observes
//! every distinct press and release.
//!
//! Masking the report would normally *eat* any key the user presses during the ~100 ms
//! burst (the classic "typo + space" losing the space). Instead, a real key pressed mid-burst
//! is detected by the same emitted-set diff — over both the NKRO bitmap and the high-usage
//! list, so even F-row / keypad / international keys are covered — **queued** onto the tail of
//! the injection ring (with the modifiers it was pressed with) and **replayed** to the host
//! once the correction drains — in press order, exactly once. The burst therefore never drops a keystroke; it
//! only reorders the delimiter to just after the correction it completes.
//!
//! # Preserving capitalisation
//!
//! A frame carries a modifier byte alongside its key, so the first letter of the correction
//! is emitted with whatever Shift was held when the typo's first letter was typed (captured
//! from the post-fold modifier byte): `teh`→`the`, but `Teh`→`The`.
//!
//! # Why the trigger is suppressed, and the backspace count
//!
//! Matching fires the instant the buffer equals a typo — before the trigger letter has been
//! put on the wire (the overlay masks it that same scan, since `record_report` sets the
//! in-flight gate before the overlay runs). The host has therefore committed exactly the
//! earlier `buf_len - 1` letters of the word, which is the number of backspaces sent; the
//! full correction is then typed. Requiring the whole buffer to be the typo (not merely end
//! with it) means a correction never fires mid-word, so a typo that is a substring of a
//! longer word is left alone.
//!
//! # State, gate and idle cost
//!
//! The enable flag and the in-flight gate are two atomics; the word buffer and the injection
//! ring live behind one blocking [`Mutex`]/`RefCell` (the project idiom), only ever touched
//! synchronously, so no borrow spans an `.await`. [`record_report`] runs each scan while
//! enabled, but only an O([`NKRO_BYTES`]) edge diff — nothing on a scan with no fresh press.
//! [`active`](Feature::active) is one relaxed load and is true only while a correction is
//! playing, so the per-scan overlay hook is wholly skipped at rest.

use core::cell::RefCell;
use core::sync::atomic::{AtomicBool, Ordering};

use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::blocking_mutex::Mutex;

use crate::features::{is_hid_letter, Ctx, Feature, FeatureId};
use crate::keycode::AutocorrectAction;
use crate::keymap::{self, Report, NKRO_BYTES, NKRO_HIGH_CAP};
use crate::kcp::{self, Status};

// The compiled dictionary: `AC_MAX_LEN`, `AC_ENTRY_COUNT`, the trie node arrays
// (`AC_LETTER`/`AC_CHILD`/`AC_SIBLING`/`AC_CORR_ID`, node 0 = root, index 0 = "none")
// and the concatenated corrections (`AC_CORR_DATA` + `AC_CORR_OFF`). Generated by
// `build.rs` whenever the `autocorrect` feature is on.
include!(concat!(env!("OUT_DIR"), "/autocorrect_data.rs"));

/// HID usage of Backspace (usage page `0x07`) — one tap per typed letter undoes the typo.
const BACKSPACE: u8 = 0x2A;

/// HID modifier bits that capitalise a letter: Left Shift (bit 1) and Right Shift (bit 5).
/// The correction's first character is emitted with whatever of these the typo's first
/// letter carried, so a sentence-initial capital survives the correction.
const SHIFT_MODS: u8 = (1 << 1) | (1 << 5);

/// Scans each injected frame is presented. At the ~1 kHz scan this is ~12 ms — longer
/// than a host poll on every transport (USB is polled each 1 ms; the 2.4 GHz dongle and BT
/// links are slower), so each synthesised press and release is observed distinctly. The
/// burst never *drops* a concurrent keystroke regardless of this value (such keys are queued
/// and replayed, see the module docs), so the dwell is a transport-margin choice, not a
/// correctness one; it is kept conservative because the wireless frame cadence cannot be
/// host-verified here.
const FRAME_DWELL: u16 = 12;

/// Injection-ring capacity in frames. The worst correction is `AC_MAX_LEN - 1` backspaces
/// plus `AC_MAX_LEN` letters, each a press frame and a release frame (`4 * AC_MAX_LEN`); the
/// remaining headroom holds the real keystrokes queued for replay while that burst plays.
const INJECT_CAP: usize = 6 * AC_MAX_LEN;
const _: () = assert!(INJECT_CAP >= 2 * (2 * AC_MAX_LEN - 1));

/// Pack a playback frame: the HID key usage in the low byte, its modifier byte in the high
/// byte. `0` is a release / gap frame (no key, no modifier).
const fn frame(key: u8, mods: u8) -> u16 {
    (key as u16) | ((mods as u16) << 8)
}

/// The autocorrect feature: just the in-flight gate. The enable flag lives in the
/// central registry bitmap ([`crate::features::is_enabled`]) like every other
/// feature's, so the GUI toggles it through the `FEATURES` group and the config blob
/// persists it; [`enabled`](Self::enabled) / [`set_enabled`](Self::set_enabled) below
/// are thin views onto that bit.
pub struct Autocorrect {
    /// Whether a correction is currently playing back — the [`active`](Feature::active)
    /// fast-path gate, so the overlay hook runs only during a burst.
    injecting: AtomicBool,
}

/// The singleton in the [`FEATURES`](crate::features::FEATURES) registry.
pub static AUTOCORRECT: Autocorrect = Autocorrect {
    injecting: AtomicBool::new(false),
};

/// The mutable word buffer and injection ring, behind the project's blocking-mutex /
/// `RefCell` discipline. Touched only synchronously on the keyboard loop, never across
/// an `.await`.
struct State {
    /// The current word's letters (HID usages), oldest first; the rolling match buffer.
    buf: [u8; AC_MAX_LEN],
    /// Letters currently in [`buf`](Self::buf).
    buf_len: usize,
    /// Set once the word outgrows the buffer: no typo is that long, so matching is
    /// suspended until the next word boundary clears it.
    overflow: bool,
    /// Shift modifier(s) held when the buffer's first letter was typed, so the correction's
    /// first character can be re-emitted capitalised. Captured on the `0 -> 1` letter edge.
    first_shift: u8,
    /// Injection ring of [`frame`]s: queued backspace / correction taps, plus any real
    /// keystrokes pressed mid-burst awaiting replay.
    queue: [u16; INJECT_CAP],
    q_head: usize,
    q_len: usize,
    /// The frame presented this dwell window (`0` = nothing held).
    cur: u16,
    /// Scans left to present [`cur`](Self::cur) before advancing.
    dwell: u16,
    /// Previous scan's emitted basic-key bitmap (the same layout as [`Report::nkro_bits`]),
    /// so a fresh press is the `current & !previous` edge of what the host actually receives.
    prev_emitted: [u8; NKRO_BYTES],
    /// Previous scan's high-usage list ([`Report::high`] — usages `>= 0x70` kept outside the
    /// bitmap), so those presses are edge-detected and replayed too, not just the bitmap keys.
    prev_high: [u8; NKRO_HIGH_CAP],
}

static STATE: Mutex<CriticalSectionRawMutex, RefCell<State>> =
    Mutex::const_new(CriticalSectionRawMutex::new(), RefCell::new(State::new()));

impl State {
    const fn new() -> Self {
        Self {
            buf: [0; AC_MAX_LEN],
            buf_len: 0,
            overflow: false,
            first_shift: 0,
            queue: [0; INJECT_CAP],
            q_head: 0,
            q_len: 0,
            cur: 0,
            dwell: 0,
            prev_emitted: [0; NKRO_BYTES],
            prev_high: [0; NKRO_HIGH_CAP],
        }
    }

    /// Fold a freshly-emitted `usage` (with the scan's final `mods`) into the word buffer.
    /// A letter extends it (capturing the first letter's Shift); Backspace shortens it; every
    /// other key is a word boundary. When `fire` and the buffer now spells a whole typo, the
    /// correction is armed (the ring is loaded) and `true` is returned. `fire` is false while
    /// a correction is already playing, so a mid-burst keystroke updates the buffer without
    /// starting a nested correction.
    fn record_key(&mut self, usage: u8, mods: u8, fire: bool) -> bool {
        match usage {
            // A letter (`a`–`z`) extends the word and is matched.
            u if is_hid_letter(u) => {
                if self.overflow {
                    return false;
                }
                if self.buf_len >= AC_MAX_LEN {
                    // Longer than any typo: it cannot match, so stop appending until the
                    // next boundary resets the buffer.
                    self.overflow = true;
                    return false;
                }
                if self.buf_len == 0 {
                    self.first_shift = mods & SHIFT_MODS;
                }
                let n = self.buf_len;
                self.buf[n] = usage;
                self.buf_len += 1;
                if fire {
                    if let Some(cid) = lookup(&self.buf[..self.buf_len]) {
                        self.load_injection(cid);
                        return true;
                    }
                }
                false
            }
            // Backspace drops the last buffered letter, tracking the host's edit.
            BACKSPACE => {
                self.buf_len = self.buf_len.saturating_sub(1);
                if self.buf_len < AC_MAX_LEN {
                    self.overflow = false;
                }
                false
            }
            // Space, Enter, Tab, digits, punctuation: a word boundary.
            _ => {
                self.buf_len = 0;
                self.overflow = false;
                false
            }
        }
    }

    /// Load the correction `cid` into the ring: a Backspace tap for every committed letter
    /// (the whole word but its suppressed trigger), then a tap of each correction letter —
    /// the first carrying the typo's Shift so capitalisation survives. The corrected word
    /// reseeds the buffer so continued typing can form a further match.
    fn load_injection(&mut self, cid: usize) {
        let backspaces = self.buf_len - 1;
        let corr = correction(cid);
        self.q_head = 0;
        self.q_len = 0;
        for _ in 0..backspaces {
            self.enqueue_tap(BACKSPACE, 0);
        }
        for (i, &u) in corr.iter().enumerate() {
            let mods = if i == 0 { self.first_shift } else { 0 };
            self.enqueue_tap(u, mods);
        }
        self.buf[..corr.len()].copy_from_slice(corr);
        self.buf_len = corr.len();
        self.overflow = false;
        self.cur = self.pop().unwrap_or(0);
        self.dwell = FRAME_DWELL;
    }

    /// Queue a tap of `key`+`mods`: the press frame then a release (gap) frame, so the host
    /// sees a distinct down and up.
    fn enqueue_tap(&mut self, key: u8, mods: u8) {
        self.push(frame(key, mods));
        self.push(0);
    }

    fn push(&mut self, f: u16) {
        if self.q_len < INJECT_CAP {
            self.queue[(self.q_head + self.q_len) % INJECT_CAP] = f;
            self.q_len += 1;
        }
    }

    fn pop(&mut self) -> Option<u16> {
        if self.q_len == 0 {
            return None;
        }
        let f = self.queue[self.q_head];
        self.q_head = (self.q_head + 1) % INJECT_CAP;
        self.q_len -= 1;
        Some(f)
    }
}

impl Autocorrect {
    /// Whether autocorrect is enabled — a view onto the central registry bitmap.
    pub fn enabled(&self) -> bool {
        crate::features::is_enabled(FeatureId::Autocorrect)
    }

    /// Enable or disable autocorrect through the central registry, which clears the
    /// in-flight correction and partial word on the off edge (via [`Feature::on_disable`])
    /// so a disable mid-burst can never strand a masked key and a re-enable starts from a
    /// clean buffer. Autocorrect is never always-on, so the switch always takes.
    pub fn set_enabled(&self, on: bool) {
        let _ = crate::features::set_enabled(FeatureId::Autocorrect as u8, on);
    }

    /// Apply an [`AutocorrectAction`] control keycode (the `AUTOCORRECT_TOGGLE`/`AUTOCORRECT_ON`/`AUTOCORRECT_OFF` press
    /// edge, dispatched by [`crate::keymap::compute_report`]).
    pub fn control(&self, action: AutocorrectAction) {
        match action {
            AutocorrectAction::Toggle => self.set_enabled(!self.enabled()),
            AutocorrectAction::On => self.set_enabled(true),
            AutocorrectAction::Off => self.set_enabled(false),
        }
    }

    /// Feed one scan's finished report into the word buffer. `emitted` is the report's
    /// basic-key bitmap ([`Report::nkro_bits`]) — what the host actually receives — and
    /// `mods` its final modifier byte. Newly-set bits are the fresh presses: each extends /
    /// resets the buffer and, on a whole-word typo match, arms the correction. While a
    /// correction is already playing, a fresh press is instead queued for replay after the
    /// burst (so no concurrent keystroke is lost) and only tracked in the buffer, never
    /// re-firing. Ignored while disabled.
    pub fn record_report(&self, emitted: &[u8; NKRO_BYTES], high: &[u8; NKRO_HIGH_CAP], mods: u8) {
        if !self.enabled() {
            return;
        }
        STATE.lock(|cell| {
            let mut st = cell.borrow_mut();
            for (byte, &cur) in emitted.iter().enumerate() {
                let mut fresh = cur & !st.prev_emitted[byte];
                while fresh != 0 {
                    let bit = fresh.trailing_zeros() as u8;
                    fresh &= fresh - 1;
                    self.fold_press(&mut st, byte as u8 * 8 + bit, mods);
                }
            }
            // High usages (`>= 0x70`) are a list, not the bitmap; a fresh one is a usage present
            // this scan but not last. Folded identically, so a high-usage key pressed mid-burst is
            // replayed, not dropped (it is a word boundary, so it can never match a typo).
            for &usage in high.iter() {
                if usage != 0 && !st.prev_high.contains(&usage) {
                    self.fold_press(&mut st, usage, mods);
                }
            }
            st.prev_emitted = *emitted;
            st.prev_high = *high;
        });
    }

    /// Fold one freshly-pressed `usage` into the word buffer / injection ring. While a
    /// correction plays, queue it for replay after the burst and track the buffer without
    /// re-firing; otherwise match it and arm a correction if it completes a typo.
    fn fold_press(&self, st: &mut State, usage: u8, mods: u8) {
        if self.injecting.load(Ordering::Relaxed) {
            st.enqueue_tap(usage, mods);
            st.record_key(usage, mods, false);
        } else if st.record_key(usage, mods, true) {
            self.injecting.store(true, Ordering::Relaxed);
        }
    }
}

/// Look up the complete word `buf` (HID usages, oldest first) in the trie. Returns the
/// correction id when the whole buffer spells a typo, walking one node per letter.
fn lookup(buf: &[u8]) -> Option<usize> {
    if buf.is_empty() {
        return None;
    }
    let mut level = AC_CHILD[0] as usize; // the root's first child
    for (i, &u) in buf.iter().enumerate() {
        let mut node = level;
        loop {
            if node == 0 {
                return None; // 0 = no such sibling
            }
            if AC_LETTER[node] == u {
                if i + 1 == buf.len() {
                    let c = AC_CORR_ID[node];
                    return (c != 0).then(|| (c - 1) as usize);
                }
                level = AC_CHILD[node] as usize;
                break;
            }
            node = AC_SIBLING[node] as usize;
        }
    }
    None
}

/// The correction usages for id `cid`, a slice into the concatenated pool.
fn correction(cid: usize) -> &'static [u8] {
    &AC_CORR_DATA[AC_CORR_OFF[cid] as usize..AC_CORR_OFF[cid + 1] as usize]
}

/// Overwrite the finished report with just the injected frame (`0` = none): the held
/// physical keys are masked for the duration of the burst, so only the synthesised
/// keystroke — its key and the frame's modifier byte — reaches the host, covering both the
/// 6KRO boot report and the NKRO bitmap.
fn present(r: &mut Report, f: u16) {
    let key = (f & 0xFF) as u8;
    let mods = (f >> 8) as u8;
    r.boot.keycodes = [0u8; 6];
    r.boot.modifier = mods;
    r.nkro_bits = [0u8; NKRO_BYTES];
    r.high = [0u8; NKRO_HIGH_CAP];
    if key != 0 {
        r.boot.keycodes[0] = key;
        keymap::nkro_record(&mut r.nkro_bits, &mut r.high, key);
    }
}

impl Feature for Autocorrect {
    fn id(&self) -> FeatureId {
        FeatureId::Autocorrect
    }

    fn name(&self) -> &'static str {
        "Autocorrect"
    }

    /// One relaxed load: the overlay hook runs only while a correction is playing back.
    fn active(&self) -> bool {
        self.injecting.load(Ordering::Relaxed)
    }

    /// Drop any in-flight correction and the partial word when the feature is switched
    /// off, so a disable mid-burst never strands a masked key and a re-enable starts from
    /// a clean buffer. Driven by the central [`set_enabled`](crate::features::set_enabled).
    fn on_disable(&self) {
        self.injecting.store(false, Ordering::Relaxed);
        STATE.lock(|cell| *cell.borrow_mut() = State::new());
    }

    /// Drive the injection: present the current frame (masking the physical keys), then
    /// advance the dwell. Once the ring drains, playback ends — but only after the physical
    /// keys lift, so a key still held from the burst is never re-emitted to the host.
    fn on_overlay(&self, _c: &Ctx, r: &mut Report) {
        STATE.lock(|cell| {
            let mut st = cell.borrow_mut();
            let phys_held = r.boot.keycodes.iter().any(|&k| k != 0);
            present(r, st.cur);
            st.dwell = st.dwell.saturating_sub(1);
            if st.dwell == 0 {
                match st.pop() {
                    Some(f) => {
                        st.cur = f;
                        st.dwell = FRAME_DWELL;
                    }
                    None => {
                        st.cur = 0;
                        if phys_held {
                            st.dwell = 1; // keep masking; re-check next scan
                        } else {
                            self.injecting.store(false, Ordering::Relaxed);
                        }
                    }
                }
            }
        });
    }

    /// The TEXT group (`0x9x`): report the enable flag and dictionary size, and toggle the
    /// feature. Other TEXT ops are [`Status::BadCmd`]; a non-TEXT group passes through.
    fn on_kcp(&self, cmd: u8, req: &[u8], out: &mut [u8]) -> Option<Status> {
        let status = match cmd {
            kcp::CMD_TEXT_AUTOCORRECT_INFO => {
                out[0] = self.enabled() as u8;
                out[1..3].copy_from_slice(&(AC_ENTRY_COUNT as u16).to_le_bytes());
                Status::Ok
            }
            kcp::CMD_TEXT_AUTOCORRECT_SET => match req[0] {
                0 => {
                    self.set_enabled(false);
                    Status::Ok
                }
                1 => {
                    self.set_enabled(true);
                    Status::Ok
                }
                _ => Status::BadArg,
            },
            // Known group, unrecognised operation (e.g. a future dictionary-upload op).
            _ if cmd >> 4 == kcp::group::TEXT => Status::BadCmd,
            _ => return None,
        };
        Some(status)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // HID usages of the letters used below (page 0x07): a = 0x04, so t/e/h are these.
    const T: u8 = 0x17;
    const E: u8 = 0x08;
    const H: u8 = 0x0B;
    const SPACE: u8 = 0x2C;
    const LSHIFT: u8 = 1 << 1;

    /// Drain the latched frame (`cur`, as `load_injection` leaves it) and the ring into
    /// `out`, skipping release/gap frames; returns the count of real taps written. Stays in
    /// `core` (no alloc), like the rest of the firmware.
    fn drain_taps(st: &mut State, out: &mut [(u8, u8)]) -> usize {
        let mut n = 0;
        let mut f = st.cur;
        loop {
            let key = (f & 0xFF) as u8;
            if key != 0 {
                out[n] = (key, (f >> 8) as u8);
                n += 1;
            }
            match st.pop() {
                Some(next) => f = next,
                None => return n,
            }
        }
    }

    /// Typing a whole typo arms the correction: `buf_len - 1` backspaces then the correction
    /// letters, with the trigger letter suppressed (never typed to the host).
    #[test]
    fn completing_a_typo_loads_backspaces_then_the_correction() {
        let mut st = State::new();
        assert!(!st.record_key(T, 0, true)); // "t"
        assert!(!st.record_key(E, 0, true)); // "te"
        assert!(st.record_key(H, 0, true)); // "teh" -> fires
        let mut taps = [(0u8, 0u8); 16];
        let n = drain_taps(&mut st, &mut taps);
        assert_eq!(
            &taps[..n],
            &[(BACKSPACE, 0), (BACKSPACE, 0), (T, 0), (H, 0), (E, 0)],
        );
    }

    /// S2: a Shift held on the typo's first letter capitalises the correction's first letter
    /// (`Teh` -> `The`), and nothing else.
    #[test]
    fn a_shifted_first_letter_capitalises_the_correction() {
        let mut st = State::new();
        st.record_key(T, LSHIFT, true); // "T" (Shift held)
        st.record_key(E, 0, true); // "e"
        assert!(st.record_key(H, 0, true)); // "h" -> fires
        let mut taps = [(0u8, 0u8); 16];
        let n = drain_taps(&mut st, &mut taps);
        assert_eq!(
            &taps[..n],
            &[(BACKSPACE, 0), (BACKSPACE, 0), (T, LSHIFT), (H, 0), (E, 0)],
        );
    }

    /// B1: a key pressed during the correction burst is queued onto the ring tail and
    /// replayed after the correction — present, in order, exactly once — never dropped.
    #[test]
    fn a_keystroke_pressed_mid_correction_is_replayed_not_lost() {
        let mut st = State::new();
        st.record_key(T, 0, true);
        st.record_key(E, 0, true);
        assert!(st.record_key(H, 0, true)); // correction armed, burst in flight

        // The user presses Space mid-burst: it is enqueued for replay (and clears the
        // buffer) without disturbing the correction frames already queued.
        st.enqueue_tap(SPACE, 0);
        st.record_key(SPACE, 0, false);

        let mut taps = [(0u8, 0u8); 16];
        let n = drain_taps(&mut st, &mut taps);
        assert_eq!(
            &taps[..n],
            &[(BACKSPACE, 0), (BACKSPACE, 0), (T, 0), (H, 0), (E, 0), (SPACE, 0)],
        );
        assert_eq!(st.buf_len, 0, "the replayed boundary clears the word buffer");
    }
}
